CREATE TABLE `customer` (
  `CUSTID` varchar(10) NOT NULL,
  `CUSNAM` varchar(30) DEFAULT NULL,
  `ADD1` varchar(30) DEFAULT NULL,
  `ADD2` varchar(30) DEFAULT NULL,
  `ADD3` varchar(30) DEFAULT NULL,
  `PHONE` varchar(15) DEFAULT NULL,
  `PHONE2` varchar(15) DEFAULT NULL,
  `PHONE3` varchar(15) DEFAULT NULL,
  `FAX1` varchar(15) DEFAULT NULL,
  `EMAIL` varchar(30) DEFAULT NULL,
  `REGION` decimal(14,2) DEFAULT NULL,
  `AREA` char(1) DEFAULT NULL,
  `TOT` decimal(14,2) DEFAULT NULL,
  `BFBAL` decimal(14,2) DEFAULT NULL,
  `ATTN` varchar(30) DEFAULT NULL,
  `ACCNO` varchar(9) DEFAULT NULL,
  `DEPT` char(1) DEFAULT NULL,
  `STATE` char(1) DEFAULT NULL,
  `CHKPMT` decimal(14,2) DEFAULT NULL,
  `CHKSALES` decimal(14,2) DEFAULT NULL,
  `CHKRET` decimal(14,2) DEFAULT NULL,
  `CHKDR` decimal(14,2) DEFAULT NULL,
  `CHKCR` decimal(14,2) DEFAULT NULL,
  `CHKBAL` decimal(14,2) DEFAULT NULL,
  `CHKDISC` decimal(14,2) DEFAULT NULL,
  `NOTES` text,
  `TICK` char(1) DEFAULT NULL,
  `PRICEGROUP` char(1) DEFAULT NULL,
  `username` varchar(10) DEFAULT NULL,
  `TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `BRNNO` char(20) DEFAULT '',
  `VATNO` varchar(20) DEFAULT '',
  `totfcur` decimal(14,2) DEFAULT NULL,
  `ccy` char(3) DEFAULT NULL,
  `xcrate` decimal(12,4) DEFAULT NULL,
  PRIMARY KEY (`CUSTID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1	
